Fix the sync BrowserView of solr maintenance If there are more items to process than the batch size, then flush is called. In the current implmenentation this leads to TypeError: commit() got an unexpected keyword argument 'soft'