fix errors in test setup caused by q.a.milestones
q.a.milestones depended on ploneintranet and this might be the cause for errors in the test setup:

::

   ConfigurationExecutionError: <type 'exceptions.KeyError'>: u'Duplicate profile ID: ploneintranet.search.upgrades:to_0009'